name: lint

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /server
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
